//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public System.Guid AssetID { get; set; }
        public System.Guid UserID { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> Persisted { get; set; }
        public string MezzanineID { get; set; }
        public Nullable<System.DateTime> MezzanineCreated { get; set; }
        public string EncodedID { get; set; }
        public Nullable<System.DateTime> EncodedCreated { get; set; }
        public Nullable<System.DateTime> PublishedStartDate { get; set; }
        public Nullable<System.DateTime> PublishedEndDate { get; set; }
        public Nullable<System.DateTime> PublishedCreated { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual User User { get; set; }
    }
}
